version: '3.7'

services:
  dev:
    image: node:12.16.1-alpine
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    working_dir: /usr/src/service
    command: npm run start:debug
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229

volumes:
  nodemodules:
    external: true
